# Generated by Django 2.1.1 on 2018-10-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='musicdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=20)),
                ('song', models.CharField(blank=True, max_length=50)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('style', models.CharField(blank=True, max_length=50)),
                ('vote', models.IntegerField(default=1000)),
            ],
        ),
    ]
