# Generated by Django 2.1.1 on 2018-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20181005_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdata',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
