# Generated by Django 2.1.1 on 2018-10-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_musicdata_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdata',
            name='vote',
            field=models.IntegerField(default=1000),
        ),
    ]
